### ISSUE TITLE
Slide Viewer label on spectrum analyzer

### ISSUE THREAD

**Issue by jpkelly** [Richard-Burns/SimpleMixer#34]
There seems to be a "Slide Viewer" label on the spectrum analyzer frequency range area which looks incorrect.
![image](https://user-images.githubusercontent.com/1377670/44999647-c1a95500-af73-11e8-9265-fefe58816bdd.png)

**Comment by Richard-Burns** [comment]
Sorry about these it looks like they are the results of me fixing a couple of things tonight and creating other issues. Currently out and about but will take a look at them when I get in. I hope you're not on a show.

**Comment by jpkelly** [comment]
Not on a show. Just checking it out because I saw activity on the project.
Cheers!

**Comment by Richard-Burns** [comment]
This should be gone in the latest version. Let me know if you spot it again. Thanks for reporting.
