### ISSUE TITLE
Toxs parameter

### ISSUE THREAD

**Issue by dithid** [Richard-Burns/SimpleMixer#35]
The toxs parameters are not shown when we click on top left, bottom left ... In order to show them we have to first click on postfx and then on them.

**Comment by Richard-Burns** [comment]
Will look into this now

**Comment by dithid** [comment]
Thanks a lot for this work ;)

**Comment by Richard-Burns** [comment]
Patched and fixed.

/simplemixer/container_gui/container_show/container_userpanel/parameter_user wasn't updating its reference despite it changing so now it is scripted from /simplemixer/container_gui/container_show/container_userpanel/chopexec1
