### ISSUE TITLE
Movies can't be scrubbed via cue

### ISSUE THREAD

**Issue by Richard-Burns** [Richard-Burns/SimpleMixer#37]
Would be handy

**Comment by franklin113** [comment]
Was experimenting with an idea for this- incorporate the Movie Player, movie engine, and external mvspecs.
Each mov tox could have it's own mvspec storing cues and other info.  Maybe populate a list of cues in the movie parameters so you can trigger them from the main window?


![Movie Player](https://user-images.githubusercontent.com/22523703/60613811-a082e200-9d99-11e9-912f-4c6c07f81738.png)

Each movie tox-

![mvspec](https://user-images.githubusercontent.com/22523703/60614290-a62cf780-9d9a-11e9-898c-c1289a33675b.png)

Probably wouldn't want to have a movie engine in each one, but that was the easiest way for the test.

**Comment by franklin113** [comment]
This cue building and playback feature was added to one of my my branches - 
https://github.com/franklin113/SimpleMixer/tree/Cue-Editor-Feature-Update
Still needs some optimization, but it seems to work pretty well so far.

**Comment by Richard-Burns** [comment]
Sorry I've been in London the past 10 days. I'll have a look at that this week now I'm back in Tokyo.
