### ISSUE TITLE
New Matrix.tox file doesn't have a locked Thumb OP

### ISSUE THREAD

**Issue by jetXS** [Richard-Burns/SimpleMixer#39]
The new Matrix.tox file doesn't have a locked Thumb OP.

I believe it is impacting performances negatively as the whole network is cooking all the time even when it is not dropped in a bin.

I think that locking the thumb OP at the end of the render chain should be the only action required to solve that issue.

Thanks,
Michel

**Comment by Richard-Burns** [comment]
I'm getting sloppy with these latest updates....oh dear. Fixed in the latest commit.
