### ISSUE TITLE
Matrix effect crashes TD

### ISSUE THREAD

**Issue by t0mekk** [Richard-Burns/SimpleMixer#40]
TD sudennly crashes when I  drop matrix effect to bank. 
Same thing when trying turn on component view in network.
Win10, Latest stable TD, GTX960M (with latest drivers).

**Comment by Richard-Burns** [comment]
Hmm I can't seem to reproduce this but I've not got a 960m machine lying around anywhere. Maybe turn off cooking and delete a few nodes and see which one it is? I might be able to find an alternative layout.

**Comment by Richard-Burns** [comment]
Driver issue then...very odd as I'm running a pretty old driver. I'll close this and see if anyone tries to reopen but we can assume it's drivers for now.

**Comment by t0mekk** [comment]
So, drivers were not the cause.  Project started once, then it began to hang as before. 

Here's working the solution:
you need to to **change registry keys** (or add if there is no such) in **regedit**

quote from Watchout's Win 10 Tweaking Guide

> It takes time to change display mode on servers with multiple high-resolution outputs (especially if using a sync card). With Windows default settings, the GPU might timeout and cause a bluescreen. To counter this, increase the timeout values as below.
> ```
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrDelay
> ```
>  should be increased to 15 seconds (default is 2 seconds, decimal value DWORD)
> ```
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrDdiDelay
> ```
>  should be increased to 60 seconds (default is 5 seconds, decimal value DWORD)
