### ISSUE TITLE
Post FX Issues

### ISSUE THREAD

**Issue by BradStephens** [Richard-Burns/SimpleMixer#45]
The post fx sliders don't seem to function correctly. If I add an effect, it takes effect immediately on the master output. Then if I take the slider down to 0, it still appears to be running at 100% on the master and preview. Then when I take the slider back up to 100%, the effect is completely disabled on master, but still works on preview. From here on out, moving the slider does nothing at all. The effect must be de-activated and re-added if you need to use it again.

Behavior I'd expect given the current UI:

When you add an effect, the slider starts at 0. The effect is fully enabled on the preview, and has no effect on the master out.
When you increase the slider, the effect is applied to the master output.

As a bonus, separate sliders for the preview and master could be nice.

**Comment by Richard-Burns** [comment]
I just spotted this too on a gig. Looks like the latest build has broken post fx functionality quite horribly. I'll build in a fix tomorrow

**Comment by Richard-Burns** [comment]
Also noted on separate sliders for preview

**Comment by Richard-Burns** [comment]
This should now be fixed for the latest official build released 2 days ago. I've taken note of the slider preview suggestion but haven't implemented yet as there's going to a pretty big overhaul for SimpleMixer 2.0 which has UI fixes, a new mixing system and mapping tools.

**Comment by BradStephens** [comment]
Awesome, thanks for your work! Have been enjoying gigging with 1.0, looking forward to 2.0 :)
