### ISSUE TITLE
Crossfade doesnt work

### ISSUE THREAD

**Issue by perottosson** [Richard-Burns/SimpleMixer#49]
Bug in crossfade. Easy fix though. The crossfade between the two composites doesnt work since the coords are incorrect between base_mix and base_addpost. 

Hopefully there will as well be an overall update since the framerate is very bad running in current stable release :)

**Comment by Richard-Burns** [comment]
Both issues should now be fixed. Sorry about the delay but I had  terrible internet between moving houses. If you still spot any issues feel free to open the issue again.
