### ISSUE TITLE
minor bug in resolution settings

### ISSUE THREAD

**Issue by perottosson** [Richard-Burns/SimpleMixer#50]
`/simplemixer/container_gui/container_settings/container_general/field2 `-> wrong value in parameter. It now says `Emulateoutputresolutionw `in both Field1 and Field2, causing the width and height to always having the same value. Change `Emulateoutputresolutionw `to `Emulateoutputresolutionh `in field2 fixes this.  

Thanks for nice application!

**Comment by Richard-Burns** [comment]
fixed...thanks for reporting these with so much detail...can get them sorted nice and quick.
