### ISSUE TITLE
Bank Mixing Modes: Only 4 usable

### ISSUE THREAD

**Issue by osterstone** [Richard-Burns/SimpleMixer#54]
On both bank mixers I can only use the top 4 modes: Add, Atop, Average and Brightest.
The rest of the list is not clickable and show no reaction. The scroll bar on the right does not move if I try to use it.

simplemixer.348.toe
Win10
TD 2020.46540
Acer Predator Helios 300
Nvidia GeForce GTX 1660Ti

**Comment by OwlCaveDreams** [comment]
This won't work with the current build...blend modes are all working in build 20625.
