### ISSUE TITLE
Custom parameter color palette 

### ISSUE THREAD

**Issue by t0mekk** [Richard-Burns/SimpleMixer#9]
RGB palette opens on output monitor when clicked first time. 
Dragging on main window helps as long as you have same session open.  Saving toe doesnt store window position.
Also, I think it's better to have 'Always at top' On and 'Cursor visible' Off parameters in perform by default :) 

/

Let me know would you better like me to post here about these small issues, or send pull requests?
Thanks for sharing btw, I was struggling building my own setup.

**Comment by Richard-Burns** [comment]
Yeah good point on that one. I think however you'd like really. If you do a pull request it'll probably get solved quicker so perhaps that is a good move. For the colour picker I had that in my head as an issue to solve too. Perhaps just having a hue offset slider is a better option than using the RGB colour parameter type. I've got a few new features coming in an update very soon. Possibly tonight...I'll merge anything you want to put in before I push though.

**Comment by t0mekk** [comment]
unfortunatelly, aint got time this night. can't wait new update.

**Comment by Richard-Burns** [comment]
The Colour parameter has now been replaced with a new float slider that is the hue offset. To keep everything uniform all tox's except the template now have their default rendering set to red and a new Colour offset and Saturation Offset slider.
